FROM node:latest

ENV LANG="en_US.UTF-8"
ENV LC_ALL="C.UTF-8"
ENV LANGUAGE="en_US.UTF-8"
ENV TERM="xterm"
ENV PATH="./node_modules/.bin/:/home/node/.npm-global/bin:$PATH"
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN mkdir -p /home/node/.npm-global/lib
RUN mkdir -p  /home/node/src
RUN rm -rf /home/node/src/*

WORKDIR /home/node/src

RUN npm set progress=false

ADD . /home/node/src

RUN npm install -g \
      @angular/cli@latest \
      flow-bin@latest \
      node-gyp@latest nodemon@latest\
      npm-check-updates@latest \
      typescript@latest

RUN npm --unsafe-perm install --prefer-offline

RUN npm run build

ENTRYPOINT ["/home/node/src/scripts/dockerStart.sh"]
