FROM node:latest

ENV LANG="en_US.UTF-8" \
    LC_ALL="C.UTF-8" \
    LANGUAGE="en_US.UTF-8" \
    TERM="xterm"

RUN mkdir -p /home/node/.npm-global && \
    rm -rf /home/node/src/* && \
    npm set progress=false

ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

ADD . /home/node/src

WORKDIR /home/node/src

#    rm -rf node_modules && \

RUN cd /home/node/src && \
    PATH=./node_modules/.bin/:$PATH && \
    npm install

RUN npm run build

ENTRYPOINT ["/home/node/src/scripts/dockerStart.sh"]
